using System.ComponentModel.DataAnnotations;

namespace ProductCatalog.Models;

// The User entity is what authentication will query against.
// We keep it intentionally minimal for the demo:
//   UserId       - PK; generated by EF core
//   Username     - the login name; unique in the DB
//   PasswordHash - named "Hash" on principle, but stored plaintext in this demo.
//                  In production: PasswordHasher<User> or BCrypt. NEVER plaintext.
//   Role         - single string like "User" or "Admin". Roles are claims. Could
//                  even use an Enum.
public class User
{
    public int UserId { get; set; }

    [Required]
    [MaxLength(50)]
    public string Username { get; set; } = string.Empty;

    [Required]
    public string PasswordHash { get; set; } = string.Empty;

    [Required]
    [MaxLength(20)]
    public string Role { get; set; } = string.Empty;
}