# This file, will define my CI/CD pipeline, that will run using Github Actions. 
# None of the stuff I define in here will be used for any sort of local work. 
# This file is written in YAML - indentation matters in YAML similar to Python

# What is the name of our pipeline, give it a meaningful name. You guys will end up 
# with two pipelines all showing up in the same UI - make sure you can keep them straight. 
name: Frontend CI

# The "on" section defines what triggers our pipeline to un
# We can think of it as "on push to main", or "on pull_request" 
# We will also add a trigger that allows us to start our pipeline manually
on:
    push: 
        branches: [main] # On pushes into main
        paths: # We can scope our workflow to trigger on specific files/directory changes
          - 'Week-4/WebStorefrontUI/**' # Double ** as a wildcard, any changes to files in this directory
          - '.github/workflows/frontend-ci.yml' # Specific file scoping
    
    pull_request:
        branches: [main] # On pull requests from another branch, into main
        paths: 
          - 'Week-4/WebStorefrontUI/**' # Double ** as a wildcard, any changes to files in this directory
          - '.github/workflows/frontend-ci.yml' # Specific file scoping

    workflow_dispatch: # On manual trigger


# We can actually grant specific permissions to our Workflow
# If we do this, we want to follow the least-privilege principle: this workflow doesn't write, push anything
# or send any webhook triggers to any outside system - all it needs to be able to do its jobs
# is read permissions. As we add to this workflow tomorrow, we can come edit this section
permissions:
    contents: read


# Since we are using a single repo that has multiple projects and we only want our pipeline
# to concern itself with out WebstorefronUI React SPA in week 4, we will use a "defaults" section
defaults:
    run:
        working-directory:  Week-4/WebStorefrontUI

# Our pipeline is split into jobs - discrete/separate concerns that our pipeline needs to accomplish. 
# By breaking things down into separate jobs, rather than one "fat" job we make our pipelines more 
# testable, easily debugged, and performant. 
# Each job is further subdivided into steps. These steps can be things like "checkout this branch in our repo"
# "run this shell command", "log into this cloud provider with these credentials", etc, etc

# We define jobs within the jobs section of the file
jobs:

    # Job 1 - we want to call eslint to perform static analysis of our code, and then run our unit tests
    lint-test:
        name: Lint and run unit tests
        runs-on: ubuntu-latest # This is probably not needed, as Runners SHOULD default to ubuntu
        steps: # Jobs are split into discrete steps that need to happen sequentially in order to complete them.
            
            # First step in our lint-test job: Checkout our repo, have the runner copy the contents of our
            # git repository onto its filesystem. 
          - name: Checkout repository 
            uses: actions/checkout@v6

            # Setup Node.js - our runners come with the bare minimum ubuntu ontop of its kernel
            # thankfully, they DO come with Docker. But they lack things like Node or the .NET SDK 
            # or runtimes, or nginx etc. So we have to instruct the runner to grab that software
          - name: Set up Node.js
            uses: actions/setup-node@v4
            with: # We can use "with" to set additional configurations/arguments for our action
                node-version: '24'
                cache: "npm"
                # One would assume that cache-dependency-path would be a relative path from the working-directory
                # Unfortunately, this is not the case. Its path-ed from the root of the repo. 
                cache-dependency-path: Week-4/WebStorefrontUI/package-lock.json
            
          - name: Install dependencies
            run: npm ci

            # Here we call EsLint and run static analysis of our code: for us some issues surfaced. 
            # It wants us to break out some functions/components into their own separate files. We aren't
            # interested in this at this time, so we'll just comment this out fow now. 
          - name: Lint
            run: npm run lint

          - name: Test
            run: npm run test:ci

    # Job 2 - we want to build our production bundle for our React SPA front end
    # Each workflow can have multiple jobs. We get control over what order they run in
    build: # By default, jobs run concurrently. So you can have multiple jobs going in the same workflow 
        name: Production build
        needs: lint-test # With "needs" we can have jobs run sequentially, one after the other ONLY
        runs-on: ubuntu-latest  # if the previous job succeeds 
        steps: 
        
          - name: Checkout repository
            uses: actions/checkout@v6

          - name: Setup Node.js 
            uses: actions/setup-node@v4
            with: 
                node-version: '24'
                cache: npm
                cache-dependency-path: Week-4/WebStorefrontUI/package-lock.json

          - name: Install dependencies
            run: npm ci
        
          - name: Build
            run: npm run build
            env: # If I have secrets/variables setup I can have the runner ask for them to avoid hardcoding values in this file
                VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }} # Thankfully the invocation syntax is the same for secrets or variables

            # A job can upload an artifact to your repo - then humans can inspect it - OR other Jobs in this or other workflows
            # can make use of that output
          - name: Upload dist artifact
            uses: actions/upload-artifact@v4
            with:
                name: webstorefront-dist
                path: Week-4/WebStorefrontUI/dist
                retention-days: 7

    docker:
        name: Docker image build
        needs: build
        runs-on: ubuntu-latest
        steps: 
        
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Download dist artifact
            uses: actions/download-artifact@v4
            with:
                name: webstorefront-dist
                path: Week-4/WebStorefrontUI/dist

          - name: Build Docker image (without push for now)
            run: docker build --build-arg VITE_API_BASE_URL=${{ vars.VITE_API_BASE_URL }} -t webstorefront-ui:ci .